name: generate-video

on:
  workflow_call:
    inputs:
      PLAYLIST:
        type: string
        required: true
    secrets:
      GH_PAT:
        required: true
  workflow_dispatch:
    inputs:
      PLAYLIST:
        type: string
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  generate-video:
    runs-on: ubuntu-latest
    steps:

      -
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GH_PAT }}

      -
        run: git lfs pull

      -
        name: Validate playlist exists
        run: |
          if [[ "$(yq '.playlists.["${{ inputs.PLAYLIST }}"].name' playlists.yml)" == "null" ]]; then
            echo "::error::Unrecognized playlist: '${{ inputs.PLAYLIST }}'"
            exit 1
          fi

      -
        name: Parse playlist data
        id: playlist-data
        run: |
          # Parse playlist data
          echo name="$(yq '.playlists.["${{ inputs.PLAYLIST }}"].name' playlists.yml)" | tee -a "$GITHUB_OUTPUT"
          echo "bg-file=$(yq '.playlists.["${{ inputs.PLAYLIST }}"].bg_file' playlists.yml)" | tee -a "$GITHUB_OUTPUT"

      -
        name: Restore .audiocache from cache
        uses: actions/cache/restore@v3
        with:
          path: .audiocache
          key: ${{ inputs.PLAYLIST }}
          fail-on-cache-miss: true

      -
        name: Install ffmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1

      -
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: pip

      -
        name: Install python modules
        run: pip install -r requirements.txt

      -
        name: Generate video
        env:
          AUDIOS_PATH: .audiocache
          BG_FILE: bg/${{ steps.playlist-data.outputs.bg-file }}
          OUTPUT_FILE: out/${{ inputs.PLAYLIST }}.mp4
        run: |
          # Generate video
          mkdir -p "$OUTPUTS_PATH"
          rm "$OUTPUT_FILE.mp4"

          ./video-generator/generate.sh

      -
        name: Open PR to add video
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          add-paths: out
          branch: video/${{ github.run_id }}/${{ inputs.PLAYLIST }}
          title: Re-generate ${{ inputs.PLAYLIST }}.mp4
          body: Generated via [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
