name: sync-playlists

on:
  pull_request:
    paths:
      - '.github/workflows/sync-play*.yml'
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref}}
  cancel-in-progress: true

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      playlists: ${{ steps.list-playlists.outputs.playlists }}
    steps:

      -
        uses: actions/checkout@v4

      -
        name: List playlists
        id: list-playlists
        run: |
          # List playlists
          echo "playlists=$(yq '.playlists | keys' -o=json --indent=0 playlists.yml)" | tee -a "$GITHUB_OUTPUT"

  sync-playlists:
    name: download (${{ matrix.playlist }})
    needs: [setup]
    uses: ./.github/workflows/sync-playlist.yml
    with:
      PLAYLIST: ${{ matrix.playlist }}
    secrets: inherit
    if: needs.setup.outputs.playlists != '[]'
    strategy:
      matrix:
        playlist: ${{ fromJson(needs.setup.outputs.playlists) }}
