name: sync-playlist

on:
  workflow_call:
    inputs:
      PLAYLIST:
        type: string
        required: true
    secrets:
      GH_PAT:
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  sync:
    runs-on: ubuntu-latest
    steps:

      -
        uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ secrets.GH_PAT }}

      -
        name: Validate playlist exists
        run: |
          if [[ "$(yq '.playlists.["${{ inputs.PLAYLIST }}"].name' playlists.yml)" == "null" ]]; then
            echo "::error::Unrecognized playlist: '${{ inputs.PLAYLIST }}'"
            exit 1
          fi

      -
        name: Parse playlist data
        id: playlist-data
        run: |
          # Parse playlist data
          echo name="$(yq '.playlists.["${{ inputs.PLAYLIST }}"].name' playlists.yml)" | tee -a "$GITHUB_OUTPUT"
          echo "playlist-id=$(yq '.playlists.["${{ inputs.PLAYLIST }}"].playlist_id' playlists.yml)" | tee -a "$GITHUB_OUTPUT"

      -
        name: Install ffmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1

      -
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies

      -
        name: Install python modules
        run: pip install -r requirements.txt

      -
        name: Create audio directory
        run: mkdir -p "playlists/${{ inputs.PLAYLIST }}/audio"

      - name: Sync playlist
        working-directory: playlists/${{ inputs.PLAYLIST }}/audio
        env:
          PLAYLIST_ID: ${{ steps.playlist-data.outputs.playlist-id }}
        run: |
          # spotdl playlist sync: https://spotdl.readthedocs.io/en/latest/usage/#syncing
          spotdl \
            --output "{list-position}.{output-ext}" \
            --format wav \
            --save-file save.spotdl \
            sync "https://open.spotify.com/playlist/${PLAYLIST_ID}"

      -
        name: Cache audio
        uses: actions/cache/save@v3
        with:
          path: playlists/${{ inputs.PLAYLIST }}/audio
          key: ${{ inputs.PLAYLIST }}-${{ github.run_id }}

