name: tag-and-release

on:
  push:
    branches:
      - main

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:

  release:
    uses: lucaspopp0/workflows/.github/workflows/tag-and-release.yml@v1
    with:
      tag-prefix:
